### ISSUE TITLE
Conflicting instructions about tiny add sign

### ISSUE THREAD

**Issue by Kulasko** [ForwardCom/manual#14]
Chapter 3.2 defines 4 bit immediate extensions as zero extended. Table 4.6 in chapter 4.2 does so, too. The table for `add` in chapter 5 however defines sign-extension. As the table for the tiny `sub` instruction is consistent with chapter 3.2 and 4.2, I assume the sign-extension in chapter 5 is just a typo?

**Comment by AgnerF** [comment]
Fixed. Thank you
