### ISSUE TITLE
Missing format 1.4 A

### ISSUE THREAD

**Issue by Kulasko** [ForwardCom/manual#15]
Starting with OPJ 60 in table 4.11 as well as OPJ 58 in the instruction descriptions, the manual references a 1.4 B format as well as an 1.4 A format. Before that, just a 1.4 format is mentioned. As Format 1.4 uses template B as defined in table 3.15, I assume format 1.4 and format 1.4 B are identical. However, table 3.15 lacks any mention of the 1.4 A variant.

**Comment by AgnerF** [comment]
You are right. Format 1.4 A is used with OPJ = 60, 61, and 63. 1.4 B is used in all other cases.  
I will make the manual clear on this in version 1.09 which will be out soon.
