### ISSUE TITLE
Subsections without sections confuse some PDF viewers

### ISSUE THREAD

**Issue by Kulasko** [ForwardCom/manual#18]
I didn't test around too much since I just use Firefox for viewing PDF files, but I tracked it down to LaTeX subsections outside of sections being the issue. I don't know if this happens if there are no sections following a block of subsections, since this case doesn't happen in the manual.

What happens is that for navigation, Firefox treats the first subsection inside a list of subsections as a section, placing all following subsections one layer below it. This makes navigating a bit inconvenient. Affected are chapter 5 before section 5.1 and chapter 9 before section 9.1.

**Comment by AgnerF** [comment]
I was aware of the error but I didn't know how to fix it. It is fixed now. Thanks for the help.

**Comment by Kulasko** [comment]
Thank you for the fast fix, although I'm afraid to say it might be incomplete.

Now every instruction has an entry in the TOC. That is okay if you are fine with it, otherwise you can maybe suppress this in the specific file. I lack the experience in LaTeX to say if this is easy to do.
Another option would be to put the categories into a new 5.1 section instead of promoting them.

Also, chapter 9 seems to be unchanged. The error, although more subtle, also exists there.

**Comment by AgnerF** [comment]
Now I have changed it so that the table of contents has 2 levels, while the bookmarks pane to the left can be expanded to 3 levels. Does it look good now?

**Comment by Kulasko** [comment]
It now looks perfect, the optional expansion also is a neat feature to have. Thanks for your work.
