### ISSUE TITLE
Margins too big

### ISSUE THREAD

**Issue by nietras** [ForwardCom/manual#2]
Since moving to 1.02 the page format has changed so the text on pages take up very little space of the actual page. That is, margins are pretty big, see below. Hope this can get fixed so we are not wasting too much paper.

![image](https://cloud.githubusercontent.com/assets/10798831/16372104/0fc15f38-3c4b-11e6-929b-266dc2fdf085.png)

**Comment by AgnerF** [comment]
It was a lot of work to convert the manual to Latex. I didn't care to spend time on making style definitions, because I just wanted to get it ready for putting on Github. Some day somebody should work on the style details.

**Comment by nietras** [comment]
Understandably, which install of latex are you using? Just if I get some time to look at it.

Why latex and not MarkDown?

**Comment by AgnerF** [comment]
I chose latex to get all word processing features, such as cross references, automatic numbering of chapters and tables, table of contents, nice tables, etc. and to make a pdf from multiple files. I am using MikTex with Texmaker as user interface.

**Comment by nietras** [comment]
Yeah markdown is pretty limited in its formatting, so latex is fine. It just adds friction to contributions etc. So it's a trade off with that.
