### ISSUE TITLE
Confusing mask usage

### ISSUE THREAD

**Issue by Kulasko** [ForwardCom/manual#20]
In the current version of the manual, it is quite difficult to find out when to apply a mask. There is no note of rule deviations in chapter 3.3, some instructions have a note, ALU + branch instructions have a note on top of chapter 5.6. Floating point branch instructions have no such note on top of chapter 5.7, but I suspect the same rule applies to them, as well.

In short, the manual could greatly benefit from clearing this up and maybe noting systematic rule deviations, such as for ALU + branch instructions, more prominently, maybe at the end of chapter 3.2.

**Comment by AgnerF** [comment]
Thank you. I will add this to the next update. Jump, call, return, and branch instructions cannot have a mask.
