### ISSUE TITLE
Pointer register encoding in chapter 3.2 is missing jump formats

### ISSUE THREAD

**Issue by Kulasko** [ForwardCom/manual#21]
I would assume format 1.6 instructions to use normal general purpose registers, while format 2.5.2 might use the special pointers, as other multi word formats do.

**Comment by Kulasko** [comment]
Additionally, single format instructions with a memory operand are also not mentioned.

**Comment by AgnerF** [comment]
Jump instructions can use general purpose registers or vector registers. Page 29 in the manual: "The instructions will use vector registers when there is an OT field and M = 1." It follows from this that jump instructions using the A and B formats can have vector registers. Jump instructions using the C and D formats can not have vector registers because there is no OT field. 
Single format instructions with memory operands can only use format 2.5.

**Comment by Kulasko** [comment]
I am sorry, I should have clarified that I am exclusively talking about the pointer register for memory operands here.

Format 1.6 has an indirect jump using a memory operand, and using THREADP, DATAP or IP here makes little sense, since the address is absolute and without offset.
On the other hand, Format 2.5.2 has a 16 bit offset, so following the rules stated in chapter 3.2, pointer register indices of 28-30 should signal the three respective special pointers.
Following by these rules, the store instruction in Format 2.5 should not use them, while the other instructions in this format do.

Chapter 3.2 strikes me like an exhaustive list on when to apply THREADP, DATAP and IP in that index range, hence my impression that these cases are missing there.

**Comment by AgnerF** [comment]
I am not sure I understand what you mean. By memory operand I mean data operand, not jump target. Format 1.6 cannot have a memory operand. No memory operands and no jump targets have absolute addresses. There is always a base pointer. THREADP, DATAP and IP are needed as base pointers for static data. In format 2.5.2, there is a data memory operand with RS as base pointer and the lower 16 bits of IM2 as offset added to RS. The upper 16 bits of IM2 indicate the jump target relative to IP.

**Comment by Kulasko** [comment]
I too am talking about a data operand in memory. Format 1.6 doesn't have such an operand in general, however, opcodes 58 to 61 do. The base pointer is referred to as 'pointer register' in chapter 3.2, thus I did use that name.
To reiterate, chapter 3.2 states that this base pointer can use any general purpose register for multi format instructions, but get r28-r30 replaced in formats with an offset of at least 16 bits.

The data operand from memory for format 1.6, opcode 58 and 59 has no offset, while opcode 60 and 61 have an 8 bit offset.
The jump instructions of format 2.5.2 use a data operand from memory with a base pointer and a 16 bit offset.
The single format instructions of format 2.5 use a data operand from memory with a base pointer and a 16 bit offset, except the store instruction at opcode 8, which uses an 8 bit offset.

None of these formats are mentioned in chapter 3.2 under the pointer register section. When applying the rules listed in chapter 3.2, the indirect jumps in format 1.6 are able to use r0-r31, while the jump instructions of format 2.5.2 and the other single format instructions of format 2.5 replace r28-r30 as their base pointer with THREADP, DATAP, and IP. For the store instruction in format 2.5, this is still unclear.

I would like the pointer register section in chapter 3.2 to explicitly assign one of the modes (replacement/no replacement) to these formats.

**Comment by AgnerF** [comment]
Now I understand what you mean. I will add format 2.5 and 2.5.2 to the formats that can use special registers as base pointers.
