### ISSUE TITLE
Unspecified destination length of vector instructions with just one broadcast immediate input

### ISSUE THREAD

**Issue by Kulasko** [ForwardCom/manual#24]
As far as I've seen, the assembler and emulator both handle this case as a scalar operation, so I propose adding a note of this case in chapter 3.2 (Coding of operands) under "Combining vectors with different lengths", as the length of the destination register is defined there.

**Comment by AgnerF** [comment]
The next update will say: 
An immediate operand will be broadcast to the vector length of the destination. If there are no other source operands then the destination will be a scalar.
