### ISSUE TITLE
Optimization: Combine increment with compare

### ISSUE THREAD

**Issue by Kulasko** [ForwardCom/manual#25]
I have not seen this optimization with any optimization level, so I assume it doesn't exist.

As the manual explains, the instruction mainly is useful for simple for loops. However, writing a for loop with the provided assembler syntax currently yields an add(1) and a compare instruction.

**Comment by AgnerF** [comment]
These cases are all optimized with optimization level 1 or higher:
```
for (int r1=0; r1 < 100; r1++) {}
for (int r1=0; r1 < r2; r1++) {}
for (int r1=1; r1 <= r2; r1++) {}
```
Assemble with: forw -ass -O2 test.as -list=test.txt

Please provide an example for the case that does not work.

**Comment by Kulasko** [comment]
I will try to construct a minimal sample later, but you can take the mandelbrot program I sent you. The main program contains three nested iterating loop, of which none receive this optimization.
I also just realized that I opened the issue on the manual repository instead of the bintools one, so I apologize.

**Comment by AgnerF** [comment]
The mandelbrot.as is optimizing OK for me. Do you have the latest version of forw.exe?
BTW, you get shorter code with int32 loop counters. Don't use unsigned counters.

**Comment by Kulasko** [comment]
I tried your provided examples with -O2 and none of them assemble to an "increment_compare" instruction, all do
```
int32 r1 = add(r1, 1)
int32 compare(r1, <goal>), jump_sbelow(eq) @_001
```
I also pulled from the bintools repository and recompiled them just before testing.

**Comment by AgnerF** [comment]
I cannot replicate your error. Even if I assemble your result
`int32 r1 = add(r1, 1)`
`int32 compare(r1, <goal>), jump_sbelow(eq) @_001`
it is optimized to increment_compare.

Please tell exactly what you are doing. Windows or Linux? Are you using the latest version of forw.exe and instruction_list.csv ?
Command line?

**Comment by Kulasko** [comment]
I am using Linux. I pulled the current version from the repo today, `instruction_list.csv` allegedly is from 2023-01-01. I compiled the tools using `make -f forw.make`. Then I created a file with this content:
```
code section execute ip align = 4
	_main function public
		for (int r1=1; r1 <= r2; r1++) {}
		return
	_main end
code end
```
I assemble it with `forw -ass -debug=1 -list=debug -O2 test.as test.ob`. I get this content in the list file:
```
// Assembly listing of file: Programs/test.as
// Fri Feb 24 00:13:26 2023

public _main: function


code    section execute align=4                         // address/4. section 1
_main: function
int32   r1 = move(1)                                    // 0000 _ 010_B 02 2 01.00 01
int32   compare(r1, r2), jump_sabove @for_1_b           // 0001 _ 160_B 24 2 01.02 02
@for_1_a: 
int32   r1 = add(r1, 1)                                 // 0002 _ 010_B 08 2 01.01 01
int32   compare(r1, r2), jump_sbeloweq @for_1_a         // 0003 _ 160_B 25 2 01.02 FE
@for_1_b: 
        return                                          // 0004 _ 163_A 3E 0 00.00.00 _

code    end
```

**Comment by AgnerF** [comment]
It appears to be an optimization bug in g++. It works with clang++ and with MS compiler.
I have made a workaround in assem5.cpp line 1434 that makes it work (g++ version 9.3.0)

**Comment by Kulasko** [comment]
That sounds quite weird, but I can confirm that the optimization works now.
