### ISSUE TITLE
Wrong claim that immediate values are not supported for sub/jump instructions

### ISSUE THREAD

**Issue by Kulasko** [ForwardCom/manual#26]
The claim is written in chapter 5.6, in the description of the instructions.
It is true that these instructions cannot be encoded in Format 1.7C. However, the assembler will happily encode a sub/jump instruction with a small constant in format 2.5.1B.

**Comment by AgnerF** [comment]
Fixed. 
Format 1.7 is used if source and destination are the same int32 register and the constant is small
