### ISSUE TITLE
Discussion: ARM v8-A Scalable Vector Extension (SVE)

### ISSUE THREAD

**Issue by nietras** [ForwardCom/manual#5]
@AgnerF seems they stole your idea ;) Note sure how the actual ISA is, though.

http://www.anandtech.com/show/10586/arm-announces-arm-v8a-with-scalable-vector-extensions-aiming-for-hpc-and-data-center

**Comment by nietras** [comment]
@AgnerF I can see here that Scalable Vector Extensions are in increments of 128-bit so not truly variable length.

![SVE Increments](http://images.anandtech.com/doci/10680/1473926218839-150708497_575px.jpg)

More from ARM here: http://www.anandtech.com/show/10680/arm-research-summit-2016-keynote-live-blog and slides here https://community.arm.com/servlet/JiveServlet/download/38-25150/ARMv8-A%20SVE%20technology%20Hot%20Chips%20v12.pdf as detailed in https://community.arm.com/groups/processors/blog/2016/08/22/technology-update-the-scalable-vector-extension-sve-for-the-armv8-a-architecture

**Comment by AgnerF** [comment]
Thanks for the links. This looks weird: Two different vector extensions to ARM: SIMD for media/image processing, and SVE for high performance scientific computing. It will be interesting to see how this develops.
